apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mar14-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar14-1 
  name: mar14-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mar14-1 
